import { z, ZodType } from 'zod';

const FreightSchema = z.array(
  z.object({
    object_created: z.string(),
    object_id: z.string(),
    object_owner: z.string(),
    shipment: z.string(),
    attributes: z.array(z.string()),
    amount: z.string(),
    currency: z.string(),
    amount_local: z.string(),
    currency_local: z.string(),
    provider: z.string(),
    provider_image_75: z.string(),
    provider_image_200: z.string(),
    servicelevel: z.object({
      name: z.string(),
      token: z.string(),
      terms: z.string(),
      extended_token: z.string(),
      parent_servicelevel: z.null().optional(),
    }),
    estimated_days: z.number().positive(),
    arrives_by: z.string(),
    duration_terms: z.string(),
    messages: z.array(z.unknown()),
    carrier_account: z.string(),
    test: z.boolean(),
    zone: z.string(),
    included_insurance_price: z.null().optional(),
    id: z.string(),
    object: z.string(),
    created_at: z.string(),
    updated_at: z.string(),
    mode: z.string(),
    service: z.string(),
    carrier: z.string(),
    rate: z.string(),
    retail_rate: z.string(),
    retail_currency: z.null().optional(),
    list_rate: z.string(),
    list_currency: z.null().optional(),
    billing_type: z.string(),
    delivery_days: z.null().optional(),
    delivery_date: z.null().optional(),
    delivery_date_guaranteed: z.boolean(),
    est_delivery_days: z.null().optional(),
    shipment_id: z.string(),
    carrier_account_id: z.string(),
  })
);

export interface FreightSchema extends ZodType<typeof FreightSchema> {}

const FreightSchemaLoop = 
    z.object({
      object_created: z.string(),
      object_id: z.string(),
      object_owner: z.string(),
      shipment: z.string(),
      attributes: z.array(z.string()),
      amount: z.string(),
      currency: z.string(),
      amount_local: z.string(),
      currency_local: z.string(),
      provider: z.string(),
      provider_image_75: z.string(),
      provider_image_200: z.string(),
      servicelevel: z.object({
        name: z.string(),
        token: z.string(),
        terms: z.string(),
        extended_token: z.string(),
        parent_servicelevel: z.null().optional(),
      }),
      estimated_days: z.number().positive(),
      arrives_by: z.string(),
      duration_terms: z.string(),
      messages: z.array(z.unknown()),
      carrier_account: z.string(),
      test: z.boolean(),
      zone: z.string(),
      included_insurance_price: z.null().optional(),
      id: z.string(),
      object: z.string(),
      created_at: z.string(),
      updated_at: z.string(),
      mode: z.string(),
      service: z.string(),
      carrier: z.string(),
      rate: z.string(),
      retail_rate: z.string(),
      retail_currency: z.null().optional(),
      list_rate: z.string(),
      list_currency: z.null().optional(),
      billing_type: z.string(),
      delivery_days: z.null().optional(),
      delivery_date: z.null().optional(),
      delivery_date_guaranteed: z.boolean(),
      est_delivery_days: z.null().optional(),
      shipment_id: z.string(),
      carrier_account_id: z.string(),
    });

export interface FreightSchemaLoop extends ZodType<typeof FreightSchemaLoop> {}
